version: "3"
networks:
    default:
        driver: bridge
services:
    exercise:
        build: .
        ports:
            - "80:80"
        volumes:
            - /app/node_modules
        command: npm run start
