name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      - name: Docker Build
        run: |
          docker build -t wchunt/exercise .
      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master
        with:
          images: wchunt/exercise
          ports: 80

      - name: Docker Push
        run: docker push wchunt/exercise
